[env:mhetesp32devkit]
platform = espressif32
board = mhetesp32devkit
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_port   = COM5
monitor_port  = COM5
upload_speed  = 115200

lib_deps =
    madhephaestus/ESP32Servo @ ^0.13.0
